### ISSUE TITLE
No secret - gem is not working

### ISSUE THREAD

**Issue by tommybernaciak** [randomizor/misfit_gem#1]
When using oauth-shine gem to connect with api, it will not return oauth_secret so the client created with this gem is not working, because it is created like this:

  @client ||= MisfitGem::Client.new(
    consumer_key: ENV["MISFIT_API_KEY"],
    consumer_secret: ENV["MISFIT_API_SECRET"],
    token: oauth_access_token,
    secret: oauth_secret
    )

client exist, but method get_summary will return empty array.

**Comment by randomizor** [comment]
You're correct. I will update the documentation as secret is not required.

I'm not having an issues getting a summary from a device though.

What range are you trying to get an activity summary of? What was your last sync time? (@client.get_device will let you know).

**Comment by tommybernaciak** [comment]
Right know I made connection with API on my own, and it is working well. I just wanted to mention that you should update readme and maybe check if everything is working properly, because it could be outdated (I saw that last commit was about 7 months ago).  :)
